/**
 * 内置 `new-novel` 工作流模板（原创长篇）。
 *
 * 人工闸放在三个高杠杆决策上：创作简报、概念锁定、主线骨架；章节草稿走
 * 多维审计 Gate，通过后由人工确认再结算状态（ADR「不要确认地狱」）。
 */

import type { WorkflowTemplate } from "../workflow/template.js";

export const NEW_NOVEL_TEMPLATE: WorkflowTemplate = {
  id: "new-novel",
  version: "2.2",
  label: "原创长篇（Canon 驱动）",
  nodes: [
    {
      id: "creative_brief",
      label: "创作简报",
      executor: "novel.brief",
      dependsOn: [],
      inputs: [],
      outputs: [{ artifactId: "creation.brief", schemaId: "creative-brief.v1" }],
      gate: { evaluator: "creative-brief-gate", required: true },
      retry: { maxAttempts: 2 },
      approval: { required: true, role: "creator" },
      idempotent: true,
      params: {},
    },
    {
      id: "concept_forge",
      label: "概念孵化",
      executor: "novel.concept-forge",
      dependsOn: ["creative_brief"],
      inputs: [{ artifactId: "creation.brief", version: "latest", optional: false }],
      outputs: [{ artifactId: "creation.concepts", schemaId: "concept-candidates.v1" }],
      gate: { evaluator: "concept-gate", required: true },
      retry: { maxAttempts: 2 },
      approval: { required: true, role: "creator" },
      idempotent: true,
      params: { candidateCount: 3 },
    },
    {
      id: "canon_build",
      label: "世界观与人物 Canon",
      executor: "novel.canon",
      dependsOn: ["concept_forge"],
      inputs: [
        { artifactId: "creation.brief", version: "latest", optional: false },
        { artifactId: "creation.concepts", version: "latest", optional: false },
      ],
      outputs: [{ artifactId: "creation.canon", schemaId: "canon-bible.v1" }],
      gate: { evaluator: "canon-gate", required: true },
      retry: { maxAttempts: 2 },
      approval: { required: false, role: "creator" },
      idempotent: true,
      params: {},
    },
    {
      id: "story_spine",
      label: "主线骨架",
      executor: "novel.spine",
      dependsOn: ["canon_build"],
      inputs: [
        { artifactId: "creation.canon", version: "latest", optional: false },
        { artifactId: "creation.brief", version: "latest", optional: false },
      ],
      outputs: [{ artifactId: "creation.spine", schemaId: "original-spine.v1" }],
      gate: { evaluator: "spine-gate", required: true },
      retry: { maxAttempts: 2 },
      approval: { required: true, role: "creator" },
      idempotent: true,
      params: {},
    },
    {
      id: "arc_plan",
      label: "卷纲规划",
      executor: "novel.arc-plan",
      dependsOn: ["story_spine"],
      inputs: [
        { artifactId: "creation.spine", version: "latest", optional: false },
        { artifactId: "creation.brief", version: "latest", optional: false },
      ],
      outputs: [{ artifactId: "creation.arcs", schemaId: "arc-plan.v1" }],
      gate: null,
      retry: { maxAttempts: 2 },
      approval: { required: false, role: "creator" },
      idempotent: true,
      params: {},
    },
    {
      id: "chapter_contracts",
      label: "章级契约",
      executor: "novel.chapter-contracts",
      dependsOn: ["arc_plan"],
      inputs: [
        { artifactId: "creation.arcs", version: "latest", optional: false },
        { artifactId: "creation.spine", version: "latest", optional: false },
        { artifactId: "creation.canon", version: "latest", optional: false },
      ],
      outputs: [{ artifactId: "creation.chapter-contracts", schemaId: "chapter-contract.v1" }],
      gate: { evaluator: "chapter-plan-gate", required: true },
      retry: { maxAttempts: 2 },
      approval: { required: false, role: "creator" },
      idempotent: true,
      params: { chapters: 3 },
    },
    {
      id: "draft_chapters",
      label: "章节正文",
      executor: "novel.draft-chapters",
      dependsOn: ["chapter_contracts"],
      inputs: [
        { artifactId: "creation.chapter-contracts", version: "latest", optional: false },
        { artifactId: "creation.canon", version: "latest", optional: false },
      ],
      outputs: [{ artifactId: "creation.drafts", schemaId: "creation-draft.v1" }],
      gate: null,
      retry: { maxAttempts: 2 },
      approval: { required: false, role: "creator" },
      idempotent: false,
      params: {},
    },
    {
      id: "chapter_audit",
      label: "多维审计",
      executor: "novel.audit",
      dependsOn: ["draft_chapters"],
      inputs: [
        { artifactId: "creation.drafts", version: "latest", optional: false },
        { artifactId: "creation.chapter-contracts", version: "latest", optional: false },
        { artifactId: "creation.canon", version: "latest", optional: false },
      ],
      outputs: [{ artifactId: "creation.audit-report", schemaId: "chapter-audit.v1" }],
      gate: { evaluator: "chapter-audit-gate", required: true },
      retry: { maxAttempts: 1 },
      approval: { required: true, role: "creator" },
      idempotent: true,
      params: {},
    },
    {
      id: "state_settlement",
      label: "状态结算",
      executor: "novel.state-settle",
      dependsOn: ["chapter_audit"],
      inputs: [
        { artifactId: "creation.drafts", version: "latest", optional: false },
        { artifactId: "creation.chapter-contracts", version: "latest", optional: false },
      ],
      outputs: [{ artifactId: "creation.state", schemaId: "state-snapshot.v1" }],
      gate: null,
      retry: { maxAttempts: 2 },
      approval: { required: false, role: "creator" },
      idempotent: true,
      params: {},
    },
  ],
};
